/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PramukaForm;

/**
 *
 * @author VIVOBOOK 14
 */
import PertemuanKeempat.MenuUtama;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DataPramuka extends javax.swing.JFrame {

    private DefaultTableModel model;
    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/kuliahPBO";
    String user = "postgres";
    String password = "kapuas02";
    InputStreamReader inputStreamReader = new InputStreamReader(System.in);
    BufferedReader input = new BufferedReader(inputStreamReader);

    /**
     * Creates new form DataPramuka
     */
    public DataPramuka() {
        initComponents();
        showTable();
        Tbldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = Tbldata.getSelectedRow();

                String NTA = Tbldata.getValueAt(row, 0).toString();
                String Nama = Tbldata.getValueAt(row, 1).toString();
                String Alamat = Tbldata.getValueAt(row, 2).toString();
                String JenisKelamin = Tbldata.getValueAt(row, 3).toString();

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        Tabel = new javax.swing.JScrollPane();
        Tbldata = new javax.swing.JTable();
        Kotak = new javax.swing.JPanel();
        NamaTabel = new javax.swing.JLabel();
        bUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        btnTambah.setBackground(new java.awt.Color(153, 255, 153));
        btnTambah.setForeground(new java.awt.Color(0, 0, 0));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        Tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NTA", "Nama", "Alamat", "Jenis Kelamin"
            }
        ));
        Tabel.setViewportView(Tbldata);

        Kotak.setBackground(new java.awt.Color(204, 102, 0));

        NamaTabel.setBackground(new java.awt.Color(255, 255, 255));
        NamaTabel.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        NamaTabel.setForeground(new java.awt.Color(255, 255, 255));
        NamaTabel.setText("DATA PRAMUKA");

        javax.swing.GroupLayout KotakLayout = new javax.swing.GroupLayout(Kotak);
        Kotak.setLayout(KotakLayout);
        KotakLayout.setHorizontalGroup(
            KotakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KotakLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(NamaTabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        KotakLayout.setVerticalGroup(
            KotakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KotakLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(NamaTabel)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        bUpdate.setBackground(new java.awt.Color(204, 204, 204));
        bUpdate.setForeground(new java.awt.Color(0, 0, 0));
        bUpdate.setText("Perbarui");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setForeground(new java.awt.Color(0, 0, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Tabel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Kotak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Kotak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Tabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus)
                    .addComponent(btnTambah))
                .addGap(146, 146, 146))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void showTable() {
        try {
            // TODO code application logi
            Class.forName(driver);
            String sql = "SELECT * FROM Pramuka ORDER BY NTA";
            conn = DriverManager.getConnection(koneksi, user, password);
            stmt = conn.createStatement();

            while (!conn.isClosed()) {

                ResultSet rs = stmt.executeQuery(sql);
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("NTA");
                model.addColumn("Nama");
                model.addColumn("Alamat");
                model.addColumn("JenisKelamin");
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("NTA"),
                        rs.getString("Nama"),
                        rs.getString("Alamat"),
                        rs.getString("JenisKelamin")
                    });
                }
                this.Tbldata.setModel(model);  // pasang ke JTable

                rs.close();
                conn.close();
            }
            stmt.close();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DataPramuka.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        InsertDialog dialog = new InsertDialog(this, true, model);
        dialog.setVisible(true);

        // kalau dialog berhasil menyimpan data, reload tabel
        if (dialog.isSaved()) {
            showTable();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        // TODO add your handling code here:
        int row = Tbldata.getSelectedRow();
        if (row != -1) {
            // ambil data dari tabel
            String NTA = Tbldata.getValueAt(row, 0).toString();
            String Nama = Tbldata.getValueAt(row, 1).toString();
            String Alamat = Tbldata.getValueAt(row, 2).toString();
            String JenisKelamin = Tbldata.getValueAt(row, 3).toString();

            // buka dialog update
            UpdateDlg dialog = new UpdateDlg(this, true, NTA, Nama, Alamat, JenisKelamin);
            dialog.setVisible(true);

            // reload tabel setelah update
            if (dialog.isUpdated()) {
                showTable();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang mau diupdate dulu!");
        }
    }//GEN-LAST:event_bUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int row = Tbldata.getSelectedRow();
        if (row != -1) {
            // ambil data dari tabel
            String NTA = Tbldata.getValueAt(row, 0).toString();
            String Nama = Tbldata.getValueAt(row, 1).toString();
            String Alamat = Tbldata.getValueAt(row, 2).toString();
            String JenisKelamin = Tbldata.getValueAt(row, 3).toString();

            // buka dialog hapus
            DeleteDlg dialog = new DeleteDlg(this, true, NTA, Nama, Alamat, JenisKelamin);
            dialog.setVisible(true);

            // reload tabel setelah delete
            if (dialog.isDeleted()) {
                showTable();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang mau dihapus dulu!");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPramuka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPramuka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPramuka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPramuka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPramuka().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Kotak;
    private javax.swing.JLabel NamaTabel;
    private javax.swing.JScrollPane Tabel;
    private javax.swing.JTable Tbldata;
    private javax.swing.JButton bUpdate;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private String getSelectedItem(String toString) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
